import Header from '@/components/Header';
import StoreProvider from '@/lib/StoreProvider';
import '@/styles/base.scss';
import cn from 'classnames';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={cn(poppins.className, poppins.variable)}>
          <Header />
          {children}
        </body>
      </html>
    </StoreProvider>
  );
}
